###

POST http://localhost:3000/auth/login Content-Type: application/json

{
    "Name": "admin",
    "Username": "newAdmin",
    "Email": "newemail@admin.se",
    "Password": "admin"

}

###
GET http://localhost:3000/list/all
